# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20170224_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.ImageField(default='/img/covers/10jpg', upload_to='/img/covers/'),
        ),
    ]
